from __future__ import annotations

import streamlit as st
import api
from common import render_page_header


def render() -> None:
    baby = api.get_baby(st.session_state.baby_id)["data"]
    data = api.get_dashboard(st.session_state.baby_id)["data"]
    vaccine = data["next_vaccination"]
    render_page_header(f"안녕하세요, {baby['baby_name']} 보호자님 👋", f"{baby['baby_name']}는 오늘 생후 {baby['age_days']}일이에요.", baby)
    st.markdown(f'''<style>
    .rem{{background:#EEF1FF;border:1px solid #C9D2FF;border-radius:15px;padding:18px 20px;margin:8px 0 16px;display:flex;justify-content:space-between;align-items:center}}.rem b{{font-size:16px}}.sub,.label{{font-size:12px;color:#778198}}.btn{{background:#fff;border:1px solid #DFE4F1;border-radius:8px;padding:7px 10px;margin-left:5px;font-size:12px}}.btnp{{background:#6374DC;color:#fff;border-color:#6374DC;font-weight:700}}.grid{{display:grid;grid-template-columns:1.55fr 1fr;gap:14px}}.card{{background:#fff;border:1px solid #E3E7F1;border-radius:16px;padding:16px;box-sizing:border-box}}.title{{font-weight:800;font-size:17px;margin-bottom:14px}}.stats{{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}}.stat{{background:#F4F6FB;border-radius:10px;padding:12px 10px;min-height:76px}}.val{{font-weight:800;font-size:16px}}.unit{{color:#6374DC;font-size:11px;font-weight:700}}.growth{{margin-top:14px;height:238px}}.line{{height:2px;background:#6374DC;transform:rotate(-3deg);margin:110px 12px 0;box-shadow:0 -8px 0 #DDE3FF}}.date{{display:inline-block;background:#EEF1FF;color:#6374DC;border-radius:10px;padding:10px;font-weight:800}}.chip{{display:inline-block;border:1px solid #DFE4F1;border-radius:7px;padding:5px 8px;font-size:11px;margin:5px 3px 0 0}}
    </style><div class="rem"><div><b>🍼 마지막 수유 후 3시간이 지났어요</b><div class="sub">서아의 배고픔 신호를 확인해 주세요.</div></div><div><span class="btn btnp">수유했어요</span><span class="btn">10분 후</span><span class="btn">건너뛰기</span></div></div><div class="grid"><div><div class="card"><div class="title">최근 7일 육아 기록 <span class="sub" style="float:right">AI로 기록하기</span></div><div class="stats"><div class="stat"><div class="label">수유</div><div class="val">7 <span class="unit">하루 평균</span></div></div><div class="stat"><div class="label">수면</div><div class="val">15시간 <span class="unit">하루 평균</span></div></div><div class="stat"><div class="label">배변</div><div class="val">5 <span class="unit">하루 평균</span></div></div></div></div><div class="card growth"><div class="title">몸무게 성장</div><div class="label">같은 성별·월령 기준과 비교한 참고 그래프</div><div class="line"></div></div></div><div><div class="card"><div class="title">다음 예방접종</div><span class="date">{vaccine['date']}</span> <b>{vaccine['name']}</b><div class="sub" style="margin:8px 0 0 52px">접종 예정일까지 {vaccine['remaining']}</div></div><div class="card" style="margin-top:14px"><div class="title">AI 육아 도우미</div><div class="label">서아의 월령과 최근 기록을 반영해 답변해 드려요.</div><span class="chip">수유 기록</span><span class="chip">수면 기록</span><br><span class="chip">주변 소아과</span><span class="chip">이유식 궁금증</span></div></div></div>''', unsafe_allow_html=True)
